#!/usr/bin/python3


import sys
from prompt import *

# Parsing arguments
args = sys.argv[1:]
is_prompt = '-p' in args
if is_prompt:
	index = args.index('-p')
	del args[index]
	command_prompt = args[index]
	del args[index]
else:
	command_prompt = ''
filename = args[0] if len(args) else None

session = prompt(filename)
session.exec('test')
